### ISSUE TITLE
The Controller still isnt working

### ISSUE THREAD

**Issue by selectiveSimile** [ryanpcmcquen/fl_studio_scripting#3]

**Comment by ryanpcmcquen** [comment]
'moved it'?

Where did you move it? What model board? What version of FL? Did you select the script under midi settings? Do you have any custom mappings on the board?

**Comment by selectiveSimile** [comment]
I figured out what I did wrong I got this second hand and didn't install the drivers. it works wonders now thanks for the code and thanks for such a speedy reply! love to change this from issue to compliment cause what you did was great.

**Comment by selectiveSimile** [comment]
okay now that im looking back into it it seems that every time i press a button that isnt the keys it has no idea what it does it just gives me the question midi at the top

**Comment by ryanpcmcquen** [comment]
What model board? What version of FL? Did you select the script under midi settings? Do you have any custom mappings on the board? Have you tried resetting the keyboard?

**Comment by selectiveSimile** [comment]
its an Axiom air 32, FL 20.8.4, I believe so i moved the script in the folder into the hardware folder, no, and i just did and now it works perfectly. I am so sorry for all this.

**Comment by ryanpcmcquen** [comment]
No worries, glad it's working!
